jobs:
name: Generate Tutorials (template)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1,4"

jobs:
  generate-tutorials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Generate tutorials from GM_APY
        env:
          GM_APY: ${{ secrets.GM_APY }}
        run: pnpm generate:tutorials

      - name: Commit and push updates
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add public/data/tutorials.json
            git commit -m "chore(tutorials): auto-generate tutorials and update catalog"
            git push
          else
            echo "No changes"
          fi

name: Generate Tutorials (template)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1,4"

jobs:
  generate-tutorials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Generate tutorials from GM_APY
        env:
          GM_APY: ${{ secrets.GM_APY }}
        run: pnpm generate:tutorials

      - name: Commit and push updates
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add public/data/tutorials.json
            git commit -m "chore(tutorials): auto-generate tutorials and update catalog"
            git push
          else
            echo "No changes"
          fi
